version: '3.8'

services:
    app:
        build: .
        container_name: personal_trainer
        expose:
            - "${SERVER_PORT}"
        depends_on:
            - shared-postgres
        environment:
            - SERVER_PORT=${SERVER_PORT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
        volumes:
            - .:/usr/src/app
        restart: always
        networks:
            - proxy_net
            - db_net

networks:
    proxy_net:
        external: true
    db_net:
        external: true
